---
version: 2

jobs:
  node:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          name: Install using yarn
          command: yarn
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run codecov
          command: yarn codecov

workflows:
  version: 2
  build:
    jobs:
      - node

