const RELATIVE_POSITIONS = {
  ID_S_RCO_FAC_DRTE: 'right',
  ID_S_RCO_FAC_GCHE: 'left'
}

const ALLOWED_RELATIVE_POSITIONS = Object.keys(RELATIVE_POSITIONS)

export {ALLOWED_RELATIVE_POSITIONS, RELATIVE_POSITIONS};
